Ordenação baseada na avaliação
pax-app/Pax_Rating pull request #3
Opened 2019-10-14 04:47 UTC by lucasdutraf

# Descrição
Neste pull request foi realizado:
* Criação das models de SERVICE e REVIEW
* Criação das rotas que retornam a média aritmética dos _rates_ de REVIEW e SERVICE baseado no user selecionado 

# Issue Relacionada
pax-app/Wiki#164

# Tipo de Mudanças

- [x] História de Usuário
- [ ] Historia Técnica
- [ ] Wiki

# Responsáveis pela revisão

@esiofreitas (PO)
@lucasdutraf (PO)
@(Membro do time de desenvolvimento que não esteja envolvido do PR)

# Checklist de document review

- [ ] Conferir se o documento é referenciado corretamente na sidebar 
- [ ] Conferir se o documento é referenciado corretamente no README da pasta em que se encontra
- [ ] Conferir se o documento cumpre com os critérios de aceitação da issue
- [ ] Conferir se o documento não possui erros de português
- [ ] Conferir se o documento possui as devidas referências

2019-10-15 15:10 UTC, rogerioo requested changes
Eu tentei conectar nas rotas com o postman, mas fica dando erro de Operação com o SQLAlchemy, mesmo com o docker rodando e conseguindo acessar o banco com o DBeaver.

2019-10-15 15:10 UTC, rogerioo commented on project/api/views.py
> +            return jsonify(createFailMessage('Insuficient service reviews')), 400
Insufficient  **

2019-10-15 15:10 UTC, rogerioo commented on project/api/views.py
> +        return jsonify(createFailMessage('Proivider not found')), 404
Provider **

2019-10-21 03:17 UTC, lucasdutraf commented on project/api/views.py
> +            return jsonify(createFailMessage('Insuficient service reviews')), 400
Resolvido!

2019-10-21 03:17 UTC, lucasdutraf commented on project/api/views.py
> +        return jsonify(createFailMessage('Proivider not found')), 404
Resolvido!

2019-10-21 03:18 UTC, lucasdutraf commented
Problemas resolvidos! Pode ser revisado.

2019-10-21 03:45 UTC, rogerioo approved these changes

2019-10-21 03:45 UTC, merged